Avoid deleting XmlRpcClient's while they are being still in use on another thread
clearpathrobotics/ros_comm pull request #3
Opened 2016-12-02 17:29 UTC by afakihcpr

* Acquire `clients_mutex_` before deleting the clients
 * Remove the timed wait for the clients to be not in use
 * Only delete and erase clients that are not in use
 * Clients that would still be in use would delete and erase themselves from `clients_` on release

@mikepurvis  @efernandez  @jasonimercer

2016-12-02 17:32 UTC, jasonimercer commented
LGTM

2016-12-02 19:27 UTC, efernandez commented on clients/roscpp/src/libros/xmlrpc_manager.cpp
> +       i->client_->close();
Indentation is wrong in these two lines: add one space to each of them.

2016-12-02 19:28 UTC, efernandez commented on clients/roscpp/src/libros/xmlrpc_manager.cpp
> +    clients_.erase(std::remove(clients_.begin(), clients_.end(), false), clients_.end());
It looks like this file follows the 80 column maximum style. You need to break this in two lines.

2016-12-02 19:29 UTC, efernandez commented on clients/roscpp/src/libros/xmlrpc_manager.cpp
> +      if (!shutting_down_)
pedantic: I'd do `if (shutting_down_)` and swap the code for the `if` branch with the `else` one. IMO it'd read better.

2016-12-02 19:29 UTC, efernandez requested changes
Only style comments, some of them need to be done. :+1:

2016-12-08 19:22 UTC, efernandez approved these changes

2016-12-08 19:22 UTC, merged

2017-01-11 15:32 UTC, deng02 commented
@efernandez   FYI this change is part of the clearpath robotics fork of ros_comm but has not yet been included in devel bundles because the distribution.yaml points to a tag that doens't include this change.  We're going to fix this today.